//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RugpViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RugpViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string AnalysisMenuLabel {
            get {
                return ResourceManager.GetString("AnalysisMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string AnalysisTabLabel {
            get {
                return ResourceManager.GetString("AnalysisTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSureTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuLabel {
            get {
                return ResourceManager.GetString("FileMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All Images.
        /// </summary>
        public static string FindAllImagesButtonLabel {
            get {
                return ResourceManager.GetString("FindAllImagesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All Images....
        /// </summary>
        public static string FindAllImagesMenuLabel {
            get {
                return ResourceManager.GetString("FindAllImagesMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all images..
        /// </summary>
        public static string FindAllImagesToolTip {
            get {
                return ResourceManager.GetString("FindAllImagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding all images....
        /// </summary>
        public static string FindingAllImagesEllipsis {
            get {
                return ResourceManager.GetString("FindingAllImagesEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex Dump.
        /// </summary>
        public static string HexDumpTabLabel {
            get {
                return ResourceManager.GetString("HexDumpTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageTabLabel {
            get {
                return ResourceManager.GetString("ImageTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoTabLabel {
            get {
                return ResourceManager.GetString("InfoTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string OpenMenuLabel {
            get {
                return ResourceManager.GetString("OpenMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a .rio file..
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string ResourcesTabLabel {
            get {
                return ResourceManager.GetString("ResourcesTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rUGPViewer.
        /// </summary>
        public static string rUGPViewer {
            get {
                return ResourceManager.GetString("rUGPViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        public static string SaveImageButtonLabel {
            get {
                return ResourceManager.GetString("SaveImageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image....
        /// </summary>
        public static string SaveImageMenuLabel {
            get {
                return ResourceManager.GetString("SaveImageMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the image as a .png file..
        /// </summary>
        public static string SaveImageToolTip {
            get {
                return ResourceManager.GetString("SaveImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Muvluv Alternative .rio file..
        /// </summary>
        public static string SelectRioFileSentence {
            get {
                return ResourceManager.GetString("SelectRioFileSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: this analysis currently loads all objects into memory. For MLA, this will use about 5.5 GB of memory. You should only proceed if your system has at least 8 GB of memory.
        ///
        ///The process will take tens of minutes. Afterwards, you will be shown a list of discovered images.
        ///
        ///Do you want to proceed?.
        /// </summary>
        public static string WarningAnalysisMemoryUsage {
            get {
                return ResourceManager.GetString("WarningAnalysisMemoryUsage", resourceCulture);
            }
        }
    }
}
